### PR TITLE
FieldSpec: add getters and setters

### PR DESCRIPTION
**Pull request by bart452**
- Simplify the procedure to set the standard getter and setter for
fields

### CODE REVIEW

**Comment by tbroyer** [comment]
How do you manage visibility of the accessors? No “helper” to create a getter or setter for a field inherited from a base class?

This would be better as helper methods creating `MethodSpec`s that you manually add to a `TypeSpec`.

**Comment by bart452** [comment]
@tbroyer Thanks for the feedback, that might be a better idea, I'll update it.

**Comment by sormuras** [comment]
#378 list more generatable `MethodSpec` candidates, based on fields with accessors.

**Comment by bart452** [comment]
#387  Seems similar to what I want to do,  if this is done from `MethodSpec`, what would be the best way to specify what getter and setter you do and don't want?
That's why it might fit better in `FieldSpec`.

**Comment by sormuras** [comment]
Let the user explicitely name the fields. Something like:
```java
FieldSpec name = ...
FieldSpec age = ...

TypeSpec.Builder builder = build("PersonBean");

Util.addFieldsAndGenerateAccessors(builder, name, age, ...);
Util.generateToStringUsingFields(buider, name, ...);
Util.generateEqualsAndHashcode(builder, name, age, ...);

TypeSpec personSpec = builder.build();

```
With `Util` being a placeholder for an arbitrary complex tool that cares for things @tbroyer mentioned. No need to integrate the desired state of turning a field to a bean property into the JavaPoet model.

**Comment by bart452** [comment]
Thanks, seems good to me, will do that. 
Probably tomorrow though.

**Comment by swankjesse** [comment]
I’m pretty reluctant on this one. I don’t think getters and setters make as much sense in 2016 as they did in 2001 when they first became popular.

Setters are good because they can implement field validation, but this code prevents that. Basically it makes the wrong thing easy.

Getters are good because they make it possible to change how the property is stored. But with mechanically generated getters that flexibility is lost.

I’d prefer to just have a helper method that does this external-to-Javapoet.

**Comment by bart452** [comment]
I agree with you here but in some cases simple getters and setters do the job.
If there is some way to do it better, please let me know.
Maybe a `BeanSpec` or something could work.

**Comment by swankjesse** [comment]
I think this is better as an independent class. Maybe in Poetry?
https://github.com/sormuras/poetry

**Pull request closed without merging**
