### PR TITLE
Add fields() and methods() accessors to TypeSpec.Builder #341

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by JakeWharton** [comment]
I wonder if we should just make the fields public. This would allow things like calling `Collections.sort` on the raw list with a custom comparator to more tightly control ordering (something that's been discussed a few times).

**Comment by sormuras** [comment]
Making them public exposes the properties to unchecked modifications - but I like the flexibilty of having access to them.
May be some of the checks executed add building/adding stuff has to re-done on `toBuild()`

**Comment by JakeWharton** [comment]
Ah, true. Good point.

**Comment by leventov** [comment]
Yeah personally I would just make the fields public. I didn't do this in PR because if they were made private initially, apparently you decided that encapsulation is more important than agility.

**Comment by swankjesse** [comment]
I like making ’em all public. It’s a _little_ annoying ’cause it prevents us from later changing say, the implementation of `TypeSpec.anonymousTypeArguments`. But that’s okay, and if we do we can rev the major version number.

**Comment by swankjesse** [comment]
@leventov wanna send a change that does public fields? Maybe just for one type to start?

**Pull request closed without merging**
