### PR TITLE
JavaFile.compile() added.

### PR DESCRIPTION
**Pull request by sormuras**
Proposal for #394

### CODE REVIEW

**Comment by sormuras** [comment]
Cleaning up the imports and empty lines and adding a "compile and instantiate" variant...

**Comment by swankjesse** [comment]
What would tools use this for?

Looking at the code I think this is interesting but doesn’t quite fit as public API in JavaPoet. In particular there’s a lot of decisions being made in here in terms of build paths, error messages, etc.

**Comment by sormuras** [comment]
* Quick check if generated code compiles
* `JavaFile.Builder.build(boolean assertCompile)` could perform a silent compile and throw an exception if compilation fails
* Use instance of generated class in tests, mock-ups and even in script-like environments
* Pass custom annotation processor (generating more `JavaFile`s) and test the results without having to introduce a dependecy to `compile-testing.jar` or others. Just use the JDK provided compiler.

Build path and error messages could be parameterized - but if you want to do some fancy stuff, roll your own `JavaFile` compiler.

**Comment by tbroyer** [comment]
Looks like something that could be useful (well, if you have a use-case for it) independently of JavaPoet; something that would ideally live in its own library (and it wouldn't even need to depend on JavaPoet IIUC, you'd just have to call `toJavaFileObject()` on your `JavaFile` and the lib would just expect a `JavaFileObject`, thus being completely independent of JavaPoet)

**Comment by swankjesse** [comment]
Let’s leave this to a separate project.

**Pull request closed without merging**
