### PR TITLE
Allow empty enums

### PR DESCRIPTION
**Pull request by h908714124**
Cherry-picked and slightly changed version of Max' original PR which has been stalled for almost a year due to legal impediments
https://github.com/square/javapoet/pull/740

### CODE REVIEW

**Comment by h908714124** [comment]
Not sure what is causing this build error. I had the same error on my machine and solved it by downgrading to JDK 8.

**Comment by JakeWharton** [comment]
```
[ERROR] /home/travis/build/square/javapoet/src/main/java/com/squareup/javapoet/TypeSpec.java:186:3: Method length is 163 lines (max allowed is 160). [MethodLength]
```

**Comment by hupfdule** [comment]
Any news on this?

The checkstyle issue seems to be resolved. And I don't see any other problems.

**Comment by JakeWharton** [comment]
Will look tomorrow

**Comment by JakeWharton** [comment]
@h908714124 you do not appear to have signed the CLA either. It is available at https://squ.re/sign-the-cla

**Comment by h908714124** [comment]
closed, I'm not signing anything, why would I?
this is github lol, get real guys

**Pull request closed without merging**
