### PR TITLE
Static imports fix in progress...

### PR DESCRIPTION
**Pull request by sormuras**
Is this fix going into the right direction?

The crazy format tests complains now...

### CODE REVIEW

**Comment by swankjesse** [comment]
I don’t think this is exactly it. Note that `null` isn’t the same as absent. It’s perfectly reasonable to pass `null` as an argument to `$L` etc.

I’m not exactly sure how this should work. Probably what we want is to change say, `JavaFile.emit()` to create a `CodeBlock` rather than immediately writing to a `CodeWriter`. Only once everything is a `CodeBlock` can we flatten correctly.

**Comment by sormuras** [comment]
Ja, makes more sense to me. Will try it that way.

**Comment by sormuras** [comment]
Moved the `importStaticForCrazyFormatsWorks()` test into an own file, utilizing parameters and checking emitted statements. Two cases fail with assumption errors, because `$N` and `$L` does not work with static imports, yet.

**Comment by sormuras** [comment]
Needs more work.

**Pull request closed without merging**
