### PR TITLE
Defines `ParameterSpec.get(VariableElement)`, `ParameterSpec.getAll(ExecutableElement)`, and `AnnotationSpec.getAll(VariableElement)`

### PR DESCRIPTION
**Pull request by perezd**
This PR encapsulates a few bits of functionality present in `MethodSpec.overriding` that should be accessible via the public API. I wanted to submit this for review, and determine if there are particular unit tests you'd like me to include.

Thanks!

### CODE REVIEW

**Comment by perezd** [comment]
Any blockers here? Thanks!

**Comment by swankjesse** [comment]
Ugh, sorry I’ve not been paying attention. Mind adding a test case for the new code?

**Comment by swankjesse** [comment]
Actually upon closer inspection I think I’ll merge as-is. Thanks for your patience @perezd !

**Comment by swankjesse** [comment]
Merged manually. Thanks!

**Pull request closed without merging**
