### PR TITLE
Add @RunWith boilerplate to tests

### PR DESCRIPTION
**Pull request by cgruber**
Add @RunWith boilerplate to tests - lets alternative test runners in other build systems pick the correct runner.

### CODE REVIEW

**Comment by cgruber** [comment]
Note - in theory, we have this in our fork, so this is totally an offer, but we can live with it if you don't want to take this on-board.  But in the interest of minimizing differences, I thought I'd throw this over the wall.

**Comment by swankjesse** [comment]
I've never understood this. Isn't this the default?

**Comment by cgruber** [comment]
It's the default in a standard JUnit4 runner via something like maven.  We
have custom runners which do funky things like identity types of tests and
restrict "short" tests from exercising the filesystem/network (you
know...make them real unit tests). etc.  It is possible we could default
things to JUnit4, or be more smart about detecting Junit4isms... but at
this point, it just runs with JUnit3 semantics (public void methods with
testFoo() naming conventions).

**Comment by swankjesse** [comment]
Got it. Everyone else upgraded to JUnit 4 in the 1990's, but it sounds like everything is more difficult at Google Scale.

**Pull request merged**
