### PR TITLE
Added char/Character to AnnotationSpec.Builder.addValue logic

### PR DESCRIPTION
**Pull request by sormuras**
Missing case `(value instanceof Character)` with test fix added.

### CODE REVIEW

**Comment by sormuras** [comment]
Lightning fast!

**Comment by swankjesse** [comment]
Probably needs escaping if the character is `'`.

**Comment by sormuras** [comment]
Escaping should be done be `$L` for every `$L` in CodeBlock, right?

**Comment by swankjesse** [comment]
Nope, `$L` is very very literal.

**Comment by sormuras** [comment]
True. PR #397 filed.

**Pull request merged**
