### PR TITLE
Allow empty enums

### PR DESCRIPTION
**Pull request by maxwalls**
As mentioned in <https://github.com/square/javapoet/issues/739>

### CODE REVIEW

**Comment by maxwalls** [comment]
> Looks good, thanks @maxwalls! Please sign our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) before I can merge the PR.

I made this contribution on behalf of my employer. Should I still sign the CLA, or should my employer sign it?

**Comment by JakeWharton** [comment]
You should consult your employer's legal department (or open source department, if you have one). The CLA is fairly standard and your contribution doesn't contain any company secrets (unless empty enums are going to reverse climate change or something...) so it shouldn't be too much of an issue. Some employers will allow you to sign the individual CLA despite contributing on behalf of your company. Others might require a corporate CLA which gives all employees permission which is doable, but more complicated and slower.

**Comment by maxwalls** [comment]
I've consulted with my employer, and they would prefer to sign a corporate CLA. Do you have a document that we can review?

**Comment by JakeWharton** [comment]
@swankjesse

**Comment by swankjesse** [comment]
@maxwalls I wasn’t able to resolve the corporate CLA by email. If you’d like to do our individual CLA, please do. Otherwise I’ll close this!

**Comment by maxwalls** [comment]
@swankjesse You can close this pull request, and then I can open a new one when we have resolved the CLA.

**Pull request closed without merging**
