### PR TITLE
support add imports

### PR DESCRIPTION
**Pull request by chengweidev**

### CODE REVIEW

**Comment by JakeWharton** [comment]
This should never be needed when using $T

**Comment by sormuras** [comment]
Duplicate of #512

**Comment by tbroyer** [comment]
@chengweidev I quickly looked at X2C's code, it looks like you could _quite easily_ replace your `StringBuffer` (sic! why not `StringBuilder`?) with a `CodeBlock.Builder` and remove your imports handling entirely so you wouldn't need that change.

**Comment by chengweidev** [comment]
@tbroyer Thank you for pointing out that using StringBuffer is a mistake, which should be using StringBuilder, but replacing StringBuffer with CodeBlock will complicate the code, for example,
 ```java
 stringBuffer. append (String. format ("% s% s = new% s (ctx); n", mName, obj, mName));
 ```
 requiring codeBlock to nest codeBlock

**Comment by chengweidev** [comment]
@sormuras   Yes, I have the same problem with him, and I think JavaFile provides an import method that makes it easier to use

**Comment by tbroyer** [comment]
```java
builder.addStatement("$T $N = new $T(ctx)", mName, obj, mName);
```
(You could also use `$1T` and avoid passing `mName` twice)

**Comment by chengweidev** [comment]
@tbroyer  Very powerful. Thank you very much.

**Pull request closed without merging**
