### PR TITLE
added JavaFile type-level commenting feature

### PR DESCRIPTION
**Pull request by snturk**
* Comments added to TypeSpec
* Tests updated with comment

### CODE REVIEW

**Comment by JakeWharton** [comment]
What is the motivation for this style of comments on types?

I suspect it will be surprising that you can call
```java
  .addComment(..)
  .addMethod(..)
  .addComment(..)
  .addMethod(..)
```
and the comments will be merged rather than interleaved among the methods.

**Comment by snturk** [comment]
The purpose of this PR is to give javapoet the ability to add comments to TypeSpec.

Thus, comments can be added only for the method, as well as for the interface or class.

An example output would be as follows:


```
package com.squareup.tacos;
    
    class Meat {
      // This is a code block comment 
    }
```

Another option is above-class comment. I can change this branch into accept just a single comment to upper line of defined class like:

```
package com.squareup.tacos;

      // This is a code block comment    
    class Meat {

    }
```

**Comment by JakeWharton** [comment]
But what purpose does it serve in comparison to Javadoc?

**Comment by snturk** [comment]
It is not always desirable to provide explanatory comments as Javadoc. In this case, an extra function is offered to the javapoet user.

For example, just adding a TODO/FIXME does not require adding Javadoc.

**Comment by JakeWharton** [comment]
Sure but you would put TODOs and FIXMEs inside the code performing the code generation. Not inside the code that is being generated.

**Comment by snturk** [comment]
Example usage:

```
TypeSpec myType = TypeSpec.classBuilder...
.addTypeComment("TODO: This type is autogenerated and incomplete!")
...
.build()
```

Then it produces that result:

```
package com.squareup.tacos;

      // TODO: This type is autogenerated and incomplete!
    class Meat {
         ...
    }
```

I think it is ok to provide that kind of feature to javapoet. Which part of that is unsuitable?

**Comment by JakeWharton** [comment]
It's not clear that there's high demand for such a feature.

You could emit such a statement in an HTML comment inside of Javadoc, for example:
```java
package com.squareup.tacos;

    /**
     * <!-- TODO: This type is autogenerated and incomplete! -->
     */
    class Meat {
         ...
    }
```

**Comment by snturk** [comment]
Of course, there is no single way to add a comment above the Type. However, all methods other than directly adding single-line comments can be counted as workarounds.


It is possible to see similar requests in issues and open PRs.

#887 #536

**Comment by JakeWharton** [comment]
We do support file-level comments which is what #536 wanted.

As to #887 that is about non-Javadoc comments on instance initializers (or you could generalize the feature request to being about members and types). But neither this PR nor theirs supports the feature in a way that we're comfortable shipping with.

**Comment by snturk** [comment]
Thanks for the feedback 👍 

I forked and applied my changes. I think these commenting features are not suitable for the project goal yet.

**Pull request closed without merging**
