### PR TITLE
add multy class support

### PR DESCRIPTION
**Pull request by JackyAnn**
generate code such as:HelloWorld.java
import java.io.Serializable;
public class HelloWorld {

}
abstract class Parent {
  protected abstract String getMessage();
}
abstract class Child {
}

### CODE REVIEW

**Comment by JackyAnn** [comment]
Multiple class declarations in one .java file
sample:
        
        String PACKAGE = "com.example.generate";
        TypeSpec child = TypeSpec.classBuilder(ClassName.get(PACKAGE, "Child"))
                                  .addModifiers(Modifier.ABSTRACT)
                                  .build();

        MethodSpec getMessage = MethodSpec.methodBuilder("getMessage")
                                          .addModifiers(Modifier.PROTECTED)
                                          .addModifiers(Modifier.ABSTRACT)
                                          .returns(String.class)
                                          .build();


        TypeSpec parent = TypeSpec.classBuilder(ClassName.get(PACKAGE, "Parent"))
                                  .addModifiers(Modifier.ABSTRACT)
                                  .addMethod(getMessage)
                                  .build();
        FieldSpec  message = FieldSpec.builder(String.class, "message")
                                      .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                                      .addModifiers(Modifier.FINAL)
                                      .initializer("\"Hello, JavaPoet!\"")
                                      .build();
        MethodSpec getMessageOvrerride = MethodSpec.methodBuilder("getMessage")
                                                   .addAnnotation(Override.class)
                                                   .addModifiers(Modifier.PROTECTED)
                                                   .returns(String.class)
                                                   .addStatement("return message")
                                                   .addModifiers()
                                                   .build();
        MethodSpec main = MethodSpec.methodBuilder("main")
                                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                                    .returns(void.class)
                                    .addParameter(String[].class, "args")
                                    .addStatement("System.out.println(\"Hello, JavaPoet!\")")
                                    .build();
        TypeSpec typeSpec = TypeSpec.classBuilder("HelloWorld")
                                    .addModifiers(Modifier.PUBLIC)
                                    .addModifiers(Modifier.FINAL)
                                    .superclass(ClassName.get(PACKAGE, parent.name))
                                    .addSuperinterface(Serializable.class)
                                    //.addType(parent)
                                    .addField(message)
                                    .addMethod(main)
                                    .addMethod(getMessageOvrerride)
                                    .build();

        JavaFile javaFile = JavaFile.builder(PACKAGE, typeSpec).addType(parent).addType(child).build();
        System.out.println(javaFile.toString());

the generate code is:
package com.example.generate;

import java.io.Serializable;
import java.lang.Override;
import java.lang.String;

public final class HelloWorld extends Parent implements Serializable {
  public static final String message = "Hello, JavaPoet!";

  public static void main(String[] args) {
    System.out.println("Hello, JavaPoet!");
  }

  @Override
  protected String getMessage() {
    return message;
  }
}
abstract class Parent {
  protected abstract String getMessage();
}
abstract class Child {
}

**Comment by JakeWharton** [comment]
What advantages does this have over separate files?

**Comment by sockeqwe** [comment]
@JakeWharton For example `AutoValueExtension` has one method `String generateClass()` which expects one String as return value containing the code for the generated class. The problem is that there is no simple way (as far as I know) to generate 2 classes as two different files in AutoValue  (except inner classes).


```java 
  @Override
    public String generateClass(
            Context context, String className, String classToExtend, boolean isFinal) {

        TypeSpec subclass = generateSomeClass();
        return JavaFile.builder(context.packageName(), subclass).build().toString();
    }
```

My (naive) solution would be to generate one java file containing one public class and the second class in the same java file (with package private visibility which would be ok in my use case). 

Is there already a way to do that with JavaPoet or do you know a better way to generate 2 classes (not inner classes) out of one `@AutoValue` annotated class?

**Comment by swankjesse** [comment]
I think that’s a problem with the AutoValue API. Defining multiple top-level classes in a single `.java` file is a bad idea, and causes grief for incremental compilers and other tools. I do not wanna support that in JavaPoet!

**Comment by swankjesse** [comment]
http://stackoverflow.com/a/2336762/40013

**Comment by JakeWharton** [comment]
Yeah that's an interesting use case. Is there another reason you don't want
to nest? Are both classes referenced by non-generated code?

**Comment by sockeqwe** [comment]
I agree! The stackoverflow answer gives an excellent explanation (I haven't thought about incremental compilation yet and I'm wondering how kotlin compiler deals with that, but that is off topic). I also consider multiple class declaration in one file as bad practice. It was just the first "workaround" that came in my mind for the autovalue API limitation, but you are absolutely right that this is not JavaPoet's problem. I was just trying to give a (very rare) use case when someone might need multiple java class definition in one file but you definitely have good arguments to not support that in JavaPoet.

**Comment by eamonnmcmanus** [comment]
The AutoValue extension API makes it easy for you to return the definition of a class that goes into the inheritance hierarchy underneath the original `@AutoValue` class. But it also gives you [access](https://github.com/google/auto/blob/facfc7e62777310282d9be1870e4b00facf692b1/value/src/main/java/com/google/auto/value/extension/AutoValueExtension.java#L62) to a [ProcessingEnvironment](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/ProcessingEnvironment.html) and you can use the [Filer](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Filer.html) from that ProcessingEnvironment to generate new classes that are not in that inheritance hierarchy.

**Comment by sockeqwe** [comment]
@JakeWharton It's a long story. In short: I use a third party library that uses reflection to load a class with a specific name (therefore I can't nest the class) and I would like to build some kind of bridge between auto value and this third party library. As already said, a very rare use case.

@eamonnmcmanus Excellent! Completely overlooked that. Thank you very much!

**Pull request closed without merging**
