### PR TITLE
License and inline annotation members

### PR DESCRIPTION
**Pull request by davti**
I have modified the code to add the following License header for JavaFile and inline AnnotationSpec members at runtime.

### CODE REVIEW

**Comment by JakeWharton** [comment]
This PR is not really reviewable because you changed the code style. Please use https://github.com/square/java-code-styles.

**Comment by JakeWharton** [comment]
Is the file comment feature not adequate for this? It will emit a series of single-line comments instead of a multi-line one. Is that a problem?

**Comment by davti** [comment]
The comments block id not in the standard java file License format so, no the  file comment feature not adequate for this.

**Comment by JakeWharton** [comment]
It's a bit annoying to need to support both. I wonder if we can just change the file comment to be multi-line if there's more than one line in the supplied string.

**Comment by davti** [comment]
"This PR is not really reviewable because you changed the code style" I use Netbeans not IntelliJ can you please provide the coding style config?

I have fixed the formatting manually please re review

**Comment by JakeWharton** [comment]
Ah, sorry. We only have available styles for IntelliJ (and thus Android Studio). I'd love to figure out a way to create them for Eclipse and NetBeans too, but it's not very highly prioritized.

**Comment by JakeWharton** [comment]
@swankjesse @ronshapiro any thoughts about https://github.com/square/javapoet/pull/579#issuecomment-326447812 ?

**Comment by davti** [comment]
apologies missed the formatting of the test files, can you send me the InteliJ formatter file I can have a look and replicate for Netbeans, Thanks,  Tim

**Comment by davti** [comment]
PS: Note the License header is slightly different from standard javadoc the comment field starts with /* as opposed to /** for javadoc

**Comment by JakeWharton** [comment]
Yep. We'd do /* for a traditional multi-line comment, not a Javadoc comment.

**Comment by davti** [comment]
I think that a multi line comment block would be a good edition as well, with the License being a specialisation of that block...

**Comment by davti** [comment]
I have had a look at the failing unit tests, I can fix the unit test string results to pass, the fixes for the most part can be achieved by adding the inlineMembers(true) to the unit test but i'm not sure if the is what the tests are to achieve...

**Comment by swankjesse** [comment]
Sorry I'm late to the review on this. I think this is completely unnecessary. Nobody should care what type of comment you use to comment your license text. This is a made up use case.

**Pull request closed without merging**
