### PR TITLE
Add methods for controlling scope of variables

### PR DESCRIPTION
**Pull request by int02h**
Utility methods that help to wrap code blocks with braces to indent variable scope:
```java
{
  int i = 0;
  String s = "";
  // and so on
}
```

### CODE REVIEW

**Comment by swankjesse** [comment]
I don’t think this is going to be very common.

**Comment by int02h** [comment]
Yes, I'm agree. But when it's necessary there is no way to do such thing. Method 'addCode' do not indent following code. Method 'beginControlFlow' inserts one space before opening brace. It looks ugly. Maybe it is more preferable to modify 'beginControlFlow' method to handle situation with whitespace at the begging of the line.

**Comment by tbroyer** [comment]
If it's only a matter of indentation (which I think it is), then use `$>` and `$<`.

```
b.addCode("{\n$>");
b.addCode("int i = 0;\n");
…
b.addCode("$<}");
```

**Comment by int02h** [comment]
Ok. You're right.

**Comment by ronshapiro** [comment]
Is using "$[" and "$]" part of the public API? If so you could use that.

**Comment by JakeWharton** [comment]
Can you do `addCode("{$[\n")` and `addCode("$]}\n")`?

**Comment by swankjesse** [comment]
Yep. Public API and documented here: https://square.github.io/javapoet/1.x/javapoet/com/squareup/javapoet/CodeBlock.html

**Pull request closed without merging**
